version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
